CREATE TABLE products ( 
  id BIGSERIAL PRIMARY KEY, 
  name VARCHAR(255) NOT NULL,
  brand_id BIGINT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  price BIGINT NOT NULL DEFAULT 0,
  discount INT NOT NULL DEFAULT 0,
  rating NUMERIC(2, 1) DEFAULT 0,
  stock INT NOT NULL DEFAULT 0,
  sold_out BIGINT NOT NULL DEFAULT 0, 
  description TEXT NOT NULL, 
  created_at TIMESTAMP DEFAULT NOW(), 
  updated_at TIMESTAMP DEFAULT NOW()
);
